subdir-ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/dtv/fc8180/inc/

obj-$(CONFIG_DTV_FC8180_SUPPORT)	+=  fc8180/src/
